---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  namespace: voting-ns
  labels:
    name: postgres-deploy
    app: postgres-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: postgres-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: postgres-app
    spec:
      containers:
      - name: postgres
        namespace: voting-ns
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: voting-ns
  labels:
    name: postgres-svc
    app: postgres-app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres-pod
    app: postgres-app