---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deploy
  namespace: voting-ns
  labels:
    name: result-deploy
    app: result-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-pod
      app: result-app
  template:
    metadata:
      name: result-pod
      namespace: voting-ns
      labels:
        name: result-pod
        app: result-app
    spec:
      containers:
      - name: result-app
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: result-svc
  namespace: voting-ns
  labels:
    name: result-svc
    app: result-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: result-pod
    app: result-app

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: result-ingress
  namespace: voting-ns
spec:
  rules:
  - host: result.mcslab.io 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: result-svc
            port: 
              number: 80