---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deploy
  namespace: voting-ns
  labels:
    name: voting-deploy
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-pod
      app: voting-app
  template:
    metadata:
      name: voting-pod
      namespace: voting-ns
      labels:
        name: voting-pod
        app: voting-app
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: voting-ns
  labels:
    name: voting-svc
    app: voting-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: voting-pod
    app: voting-app

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-ingress
  namespace: voting-ns
spec:
  rules:
  - host: voting.mcslab.io 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: voting-svc
            port: 
              number: 80