---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  namespace: voting-ns
  labels:
    name: worker-deploy
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: worker-app
  template:
    metadata:
      name: worker-app-pod
      namespace: voting-ns
      labels:
        name: worker-app-pod
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v1