---
apiVersion: v1
kind: Service
metadata:
  name: result-svc
  labels:
    name: result-svc
    app: voting-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: result-pod
    app: voting-app
